### ISSUE TITLE
Feature Request: Option to enable URL bar

### ISSUE THREAD

**Issue by HaBe2305** [Foldex/AdwSteamGtk#92]
While I'd love to stay with Adw, currently it's not an option for me because it's removing the URL bar at the top which I'm using frequently in communications on Steam and externally.
So adding a toggle for that to settings would be much appreciated.

**Comment by Foldex** [comment]
This sort of issue is better suited for the actual theme's issue tracker, not here.
This is just a frontend installer for it, and I'd prefer to not diverge from the upstream.

That said, a very basic version of this should be possible by adding this to your custom css.
Might not be the prettiest solution, but should more or less function.

![Image](https://github.com/user-attachments/assets/dcf0e892-6acc-4579-aa19-2766ca14ba24)

```css
body.DesktopUI
{
  div._1bGewp3tfzqAF6fVTFFUOz
  {
    div._2m_orETo6AghzAnc0sISCt
    {
      display: flex !important;
      -webkit-app-region: no-drag;
    }
  }
}
```
